create table fit_users (
  id integer primary key generated by default as identity,
  user_name text not null unique,
  password text not null,
  full_name text not null,
  date_created timestamp default now() not null
);