create table days_table (
  id integer primary key generated by default as identity,
  day_name text not null,
  weekid integer references weeks_table(id)
);

create table muscle_group_table (
  id integer primary key generated by default as identity,
  muscle_name text not null,
  muscle_pictures text,
);