create table exercises_table (
  id integer primary key generated by default as identity,
  exercise_name text not null,
  exercise_how_to text not null,
  muscle_group_id integer references muscle_group_table(id),
  video text not null,
  is_check boolean not null default false
);