create table exercise_tracking (
  id integer primary key generated by default as identity,
  max_value INTEGER,
  exercise_id integer references exercises_table(id),
  day_id integer references days_table(id),
  user_id integer references fit_users(id),
  date_created timestamp default now() not null
);