create table custom_list (
  id integer primary key generated by default as identity,
  max_value_1 INTEGER,
  max_value_2 INTEGER,
  max_value_3 INTEGER,
  max_value_4 INTEGER,
  max_value_5 INTEGER,
  max_value_6 INTEGER,
  max_value_7 INTEGER,
  max_value_8 INTEGER,
  max_value_9 INTEGER,
  max_value_10 INTEGER,
  max_value_11 INTEGER,
  max_value_12 INTEGER,
  exercise_id integer references exercises_table(id),
  date_created timestamp default now() not null,
  user_id integer references fit_users(id)
);