create table custom_list (
  id integer primary key generated by default as identity,
  max_value INTEGER
  exercise_id integer references exercises_table(id),
  date_created timestamp default now() not null,
  user_id integer references fit_users(id)
);

